var imageUrls = [
    
    "img/art/2024-04-10,1000,1080,Aly,1,Salvier Willowmire,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-10,1000,1080,Aly,1,Selthy Willowmire,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-10,1000,1080,Aly,1,Paige Noname,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-10,1000,1080,Aly,1,Saturi,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-10,1000,1080,Aly,1,Lance Amblecrown,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-08,1920,1800,Marlia,0,digital,full color,game,RHH,Runaways Happy Hour,lute,music,background,project,,.png",
    "img/art/2024-04-08,1000,1080,Aly,1,Leif,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,ghost,project,,.png",
    "img/art/2024-04-08,1000,1080,Aly,1,Alura Draconica,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-08,1000,1080,Aly,1,Mars,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-08,1000,1080,Aly,1,Alice Daylily,digital,full color,torso,game,RHH,Runaways Happy Hour,sprite,project,,.png",
    "img/art/2024-04-03,1920,1080,Aly,2,Alice Daylily,Mars,digital,full color,bust,game,RHH,Runaways Happy Hour,GAME OA,game over,try again,project,,.png",
    "img/art/2023-04-19,1600,1600,Artbreeder AI,1,Penelope Namishia,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpeg",
    "img/art/2023-04-19,1600,1600,Artbreeder AI,1,Keth,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpeg",
    "img/art/2023-04-19,1600,1600,Artbreeder AI,1,Keith,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpeg",
    "img/art/2023-04-19,1600,1600,Artbreeder AI,1,Hadiyah Safak,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpeg",
    "img/art/2023-04-19,1600,1600,Artbreeder AI,1,Fana Pineclaw,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpeg",
    "img/art/2023-04-19,1600,1600,Artbreeder AI,1,Darrak Karel,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpeg",
    "img/art/2023-01-11,973,1061,Aly,2,Alice Daylily,Mars,streetracer au,digital,some color,bust,nightlily,crimson,whiplash,bedtime,freshman,,.jpg",
    "img/art/2023-01-26,1000,1080,Aly,2,Alice Daylily,Mars,misc au,digital,full color,full body,nightlily,storybook,bear,cute,,.png",
    "img/art/2022-12-25,1100,1100,Miyuki,1,Lance Amblecrown,digital,full color,bust,potion,confused,,.png",
    "img/art/2022-12-25,2600,2200,Chris,1,Lance Amblecrown,digital,full color,full body,eldritch blast,,.png",
    "img/art/2022-12-21,999,771,Aly,2,Mars,Osyris,village au,digital,some color,torso,letter,idiot brother,bird,pumpkin,comic,funny,,.jpg",
    "img/art/2022-12-20,1000,1080,Aly,1,Osyris,village au,digital,some color,torso,first born,,.jpg",
    "img/art/2022-12-19,836,1080,Aly,2,Mars,Osyris,village au,digital,some color,bust,nightlily,funny,comic,,.jpg",
    "img/art/2022-11-23,772,627,Aly,2,Mars,Selthy Willowmire,digital,some color,bust,nightlily,funny,bully,theyre siblings your honor,,.png",
    "img/art/2022-11-16,1000,1080,Aly,2,Alice Daylily,Mars,digital,some color,torso,nightlily,hand,kiss,love,,.jpg",
    "img/art/2022-07-26,1000,1080,Aly,7,Alice Daylily,Paul Daylily,Mary Daylily,Ephius Daylily,Argo,Julius,Sydney,digital,some color,head,backstory summary,summary,backstory,,.png",
    "img/art/2022-07-24,1079,1074,Artbreeder AI,1,Selthy Willowmire,digital,full color,bust,artbreeder,ai,generated by marlia,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Salvier Willowmire,digital,full color,bust,artbreeder,ai,generated by marlia,,.jpg",
    "img/art/2022-07-24,1079,1074,Artbreeder AI,1,Paige Noname,digital,full color,bust,artbreeder,ai,generated by miyuki,,.jpg",
    "img/art/2022-07-24,1080,1068,Artbreeder AI,1,Tove,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Paul Daylily,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Mary Daylily,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1079,1074,Artbreeder AI,1,Mars,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Lance Amblecrown,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Ephius Daylily,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Alura Draconica,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-24,1080,1074,Artbreeder AI,1,Alice Daylily,digital,full color,bust,artbreeder,ai,generated by aly,,.jpg",
    "img/art/2022-07-22,952,836,Aly,1,Mars,digital,no color,bust,annoyed,,.png",
    "img/art/2022-07-16,512,893,Aly,1,Mars,digital,some color,bust,character,information,reference,,.png",
    "img/art/2022-07-16,512,893,Aly,1,Alice Daylily,digital,some color,bust,character,information,reference,,.png",
    "img/art/2022-05-22,1700,1700,Marlia,1,Selthy Willowmire,streetracer au,digital,full color,full body,tokyo drifting,magazine,cover,glass animals,,.jpg",
    "img/art/2022-05-22,1491,1845,Marlia,1,Salvier Willowmire,streetracer au,digital,full color,torso,femboi,vogue,magazine,cover,,.jpg",
    "img/art/2022-05-22,1000,1080,Aly,2,Alice Daylily,Mars,streetracer au,digital,full color,full body,nightlily,whiplash,crimson,,.jpg",
    "img/art/2022-05-22,1000,1080,Aly,1,Alice Daylily,streetracer au,digital,full color,torso,whiplash,masked driver,nascar,magazine,cover,,.jpg",
    "img/art/2022-04-05,3024,4032,Aly,2,Mars,Alice Daylily,traditional,full color,bust,nightlily,black out poem,poetry,,.jpg",
    "img/art/2022-03-09,1000,1080,Aly,2,Mars,Alice Daylily,misc au,digital,full color,bust,nightlily,ethereal,,.png",
    "img/art/2022-03-04,973,821,Aly,1,Mars,misc au,digital,no color,full body,literature,teacher,professor,poetry,school,,.png",
    "img/art/2022-01-24,1000,1080,Aly,1,Mars,digital,full color,full body,redesign,,.jpg",
    "img/art/2022-01-17,1079,825,Miyuki,1,Paige Noname,digital,no color,full body,redesign,,.png",
    "img/art/2022-01-03,999,851,Aly,4,Alice Daylily,Mars,Lance Amblecrown,Penelope Namishia,digital,no color,bust,portraits,,.jpg",
    "img/art/2021-12-16,3024,4032,Miyuki,1,Hadiyah Safak,traditional,no color,bust,sketch,notebook,,.jpg",
    "img/art/2021-12-16,3024,4032,Miyuki,1,Paige Noname,traditional,no color,bust,sketch,notebook,,.jpg",
    "img/art/2021-11-27,1067,799,Aly,2,Alice Daylily,Mars,digital,no color,bust,nightlily,morning,,.jpg",
    "img/art/2021-11-18,3024,4032,Aly,7,Alice,Mars,Alura,Paige,Selthy,Salvier,Lance,modern au,traditional,some color,bust,sociology,outfit,,.jpg",
    "img/art/2021-11-14,1884,730,Miyuki,2,Paige Noname,Hadiyah Safak,digital,full color,bust,monastery,backstory,young,comic,,.png",
    "img/art/2021-10-30,999,762,Aly,4,Mars,Selthy Willowmire,Salvier Willowmire,Ponder,agape au,digital,no color,full body,training,sword,again,,.jpg",
    "img/art/2021-10-27,950,722,Aly,2,Mars,Alice Daylily,agape au,digital,no color,bust,nightlily,,.png",
    "img/art/2021-09-28,964,857,Aly,1,Mars,sins au,digital,some color,bust,sloth,smoking,dot dot dot,,.jpg",
    "img/art/2021-07-15,1000,1080,Aly,2,Alice Daylily,Mars,digital,full color,head,nightlily,eyes,eye,eye reference,reference,,.jpg",
    "img/art/2021-07-12,739,893,Aly,1,Alice Daylily,digital,full color,bust,pretty,pink,colors,magic,,.png",
    "img/art/2021-07-10,1000,1080,Aly,2,Terry Crews,Leif,digital,full color,full body,redesign,funny,grow up,says you,,.png",
    "img/art/2021-07-07,524,467,Aly,1,Alice Daylily,digital,full color,bust,icon,pfp,pink,side,side profile,,.jpg",
    "img/art/2021-07-07,1125,1214,Aly,1,Alice Daylily,digital,full color,bust,icon,pfp,orange,,.jpg",
    "img/art/2021-07-06,534,653,Aly,1,Mars,digital,full color,bust,i think i got the date wrong on this one but dont tell anyone,,.jpg",
    "img/art/2021-06-23,1000,1080,Aly,1,Mars,digital,some color,full body,study,mars study,information,reference,,.png",
    "img/art/2021-06-23,1126,1304,Aly,1,Alice Daylily,digital,some color,bust,she do be looking,,.jpg",
    "img/art/2021-06-21,493,545,Aly,1,Sydney,digital,full color,bust,redesign,,.png",
    "img/art/2021-06-21,817,732,Aly,1,Julius,digital,full color,bust,redesign,,.png",
    "img/art/2021-06-21,968,863,Aly,1,Ephius Daylily,digital,full color,bust,redesign,,.png",
    "img/art/2021-06-21,427,502,Aly,1,Argo,digital,full color,bust,redesign,,.png",
    "img/art/2021-06-14,1000,1080,Aly,1,Paul Daylily,digital,full color,bust,ship,captain,this is your ship and you are the captain,,.png",
    "img/art/2021-06-12,1000,1080,Aly,1,Mars,digital,full color,full body,redesign,,.png",
    "img/art/2021-06-12,1000,1080,Aly,0,digital,some color,,equipment,reference,information,,.jpg",
    "img/art/2021-06-04,1000,1080,Aly,1,Alice Daylily,digital,full color,full body,redesign,,.png",
    "img/art/2021-05-27,603,713,Aly,1,Fana Pineclaw,digital,full color,torso,redesign,peace sign,,.png",
    "img/art/2021-05-20,720,733,Aly,1,Alice Daylily,streetracer au,digital,some color,bust,whiplash,no,x,embarrassed,,.png",
    "img/art/2021-05-19,494,707,Aly,1,Alice Daylily,streetracer au,digital,full color,full body,whiplash,design,,.jpg",
    "img/art/2021-05-19,862,798,Aly,1,Mars,streetracer au,digital,full color,bust,crimson,smoking,design,,.png",
    "img/art/2021-05-12,850,850,Marlia,1,Selthy Willowmire,agape au,digital,no color,bust,ruler,the ruler,queen,the queen,royalty,kingdom,slay,,.jpg",
    "img/art/2021-05-12,555,757,Aly,1,Mars,agape au,digital,no color,torso,armor,,.png",
    "img/art/2021-05-12,870,767,Aly,1,Mars,agape au,digital,some color,bust,embarrassed,flustered,blushing,surely you jest your majesty ,,.png",
    "img/art/2021-05-11,980,787,Aly,1,Mars,agape au,digital,some color,bust,good,blue,honor to serve the crown,,.png",
    "img/art/2021-05-11,952,768,Aly,1,Mars,agape au,digital,some color,bust,corrupt,red,honor to serve the crown,,.png",
    "img/art/2021-05-11,852,745,Aly,1,Alice Daylily,agape au,digital,some color,bust,glasses,,.png",
    "img/art/2021-04-18,1000,1080,Aly,3,Mars,Leo,Ponder,digital,some color,full body,young mars,mars,backstory,comic,,.png",
    "img/art/2021-04-17,921,743,Aly,2,Alice Daylily,Mars,misc au,digital,full color,bust,nightlily,personality swap,swap,personality,,.jpg",
    "img/art/2021-04-15,633,616,Aly,1,Leo,digital,some color,bust,original,,.png",
    "img/art/2021-04-14,1093,1269,Aly,1,Mars,sins au,digital,some color,bust,sloth,,.jpg",
    "img/art/2021-03-29,480,613,Aly,1,Mars,digital,full color,bust,annoyed,,.jpg",
    "img/art/2021-03-23,786,682,Aly,1,Mars,misc au,digital,full color,bust,gargoyle,chernabog,fantasia,costume,disney,,.png",
    "img/art/2021-03-23,856,823,Aly,1,Alice Daylily,misc au,digital,full color,bust,ursula,the little mermaid,little mermaid,villian,costume,disney,,.png",
    "img/art/2021-03-17,579,723,Aly,1,Mars,digital,some color,bust,redesign,,.png",
    "img/art/2021-03-09,1000,1080,Aly,1,Mars,cyberpunk au,digital,full color,torso,perserverance,design,,.png",
    "img/art/2021-03-09,902,909,Aly,1,Alice Daylily,cyberpunk au,digital,full color,torso,D4Y-LLY,design,,.jpg",
    "img/art/2021-02-22,675,505,Aly,1,Mars,band au,digital,full color,bust,outfit,airpods,orange,,.jpg",
    "img/art/2021-02-22,615,550,Aly,1,Alice Daylily,band au,digital,full color,bust,outfit,blue,,.jpg",
    "img/art/2021-02-18,1000,1080,Aly,2,Mars,Alice Daylily,band au,digital,some color,full body,nightlily,call,angry boyfriend speaking,,.jpg",
    "img/art/2021-02-13,1000,1080,Aly,1,Mars,band au,digital,some color,bust,singing,playing,playing keyboard,keyboard,microphone,shouting,,.jpg",
    "img/art/2021-02-12,512,704,Aly,1,Mars,band au,digital,full color,bust,smoking,,.png",
    "img/art/2021-02-12,567,1065,Aly,1,Alice Daylily,band au,digital,full color,torso,outfit,stylish,,.png",
    "img/art/2021-02-11,3024,4032,Miyuki,1,Alice Daylily,band au,traditional,no color,full body,concert,singing,microphone,,.jpg",
    "img/art/2021-02-05,388,600,Aly,2,Mars,Alice Daylily,digital,full color,bust,nightlily,information,information sheet,ship,reference,,.jpg",
    "img/art/2021-02-05,903,1168,Aly,1,Mars,digital,full color,bust,talking,,.jpg",
    "img/art/2021-02-05,1126,1073,Aly,1,Mars,digital,full color,bust,looking down,,.jpg",
    "img/art/2021-02-03,1125,1179,Aly,2,Mars,Ponder,digital,some color,full body,young mars,young,backstory,comic,kill you,,.jpg",
    "img/art/2021-02-02,824,327,Aly,2,Mars,Selthy Willowmire,digital,some color,torso,i guess i do love her,pathetic,softy,love,nightlily,,.jpg",
    "img/art/2021-02-01,960,898,Aly,1,Alice Daylily,digital,full color,full body,staff,stick,glowing,outfit,,.jpg",
    "img/art/2021-01-24,1920,1080,Aly,6,Selthy Willowmire,Alice Daylily,Mars,Alura Draconica,Paige Noname,Salvier Willowmire,digital,full color,full body,party,runaways,full party,party picture,,.png",
    "img/art/2021-01-22,1080,1350,Marlia,1,Selthy Willowmire,digital,full color,full body,outfit,reference,character,,.jpg",
    "img/art/2021-01-20,968,981,Aly,3,Mars,Paige Noname,Selthy Willowmire,digital,full color,full body,tavern,talking,siblings,theyre siblings your honor,,.jpg",
    "img/art/2021-01-20,950,817,Aly,1,Mars,digital,no color,bust,spitting out drink,panic,panik,surprise,shocked,,.png",
    "img/art/2021-01-11,1008,1310,Aly,1,Mars,digital,no color,bust,panic,panik,,.jpg",
    "img/art/2020-12-24,905,1258,Aly,1,Alice Daylily,traditional,some color,full body,happy,stick,staff,idk what it is,,.jpg",
    "img/art/2020-12-23,871,1474,Aly,1,Ephius Daylily,traditional,some color,full body,leaning,drink,young,,.jpg",
    "img/art/2020-12-23,894,1394,Aly,1,Julius,traditional,some color,full body,leaning,stick,,.jpg",
    "img/art/2020-12-23,1126,654,Aly,4,Julius,Argo,Sydney,Ephius Daylily,traditional,some color,bust,confident,funny,,.jpg",
    "img/art/2020-12-19,1126,1078,Aly,1,Mars Antagonist,traditional,some color,bust,enemy,tribe,kid,child,young,,.jpg",
    "img/art/2020-12-19,1125,945,Aly,2,Mars,Mars Antagonist,traditional,some color,bust,enemy,tribe,backstory,lore,taller,shorter,,.jpg",
    "img/art/2020-12-19,1126,945,Aly,1,Mars Antagonist,traditional,no color,bust,tribe,enemy,adult,,.jpg",
    "img/art/2020-12-15,1101,1080,Aly,5,Mars,Alice Daylily,Paige Noname,Selthy Willowmire,Salvier Willowmire,traditional,some color,full body,mistletoe,nightlily,christmas,,.jpg",
    "img/art/2020-12-15,1012,820,Aly,2,Mars,Alice Daylily,traditional,some color,bust,mistletoe,nightlily,kiss,kiss cheek,,.jpg",
    "img/art/2020-12-03,985,1276,Aly,1,Alura Draconica,traditional,some color,full body,redesign,,.jpg",
    "img/art/2020-11-30,1126,1057,Aly,1,Alura Draconica,modern au,traditional,some color,full body,yoga,,.jpg",
    "img/art/2020-11-27,1627,522,Aly,2,Mars,Alura Draconica,modern au,traditional,some color,torso,hat,comic,funny,,.jpg",
    "img/art/2020-11-26,628,764,Aly,1,Mars,modern au,traditional,some color,bust,laugh,laughing,director,,.jpg",
    "img/art/2020-11-24,1126,1139,Aly,1,Paige Noname,modern au,traditional,some color,bust,cry,dot dot dot,,.jpg",
    "img/art/2020-11-23,957,1506,Aly,2,Mars,Alice Daylily,modern au,traditional,some color,bust,nightlily,swing,height,,.jpg",
    "img/art/2020-11-22,1126,751,Aly,2,Paige Noname,Mars,modern au,traditional,some color,bust,prank,prank call,pizza,comic,,.jpg",
    "img/art/2020-11-22,644,813,Marlia,1,Salvier Willowmire,modern au,digital,full color,bust,makeup,makeup artist,brush,brushes,,.png",
    "img/art/2020-11-22,973,1112,Aly,1,Mars,digital,full color,bust,side,side profile,,.png",
    "img/art/2020-11-21,984,1539,Aly,1,Alice Daylily,traditional,some color,full body,staff,swoosh,pink,magic,,.jpg",
    "img/art/2020-11-21,1100,701,Aly,2,Lance Amblecrown,Mars,modern au,traditional,some color,bust,recording,eating,funny,comic,,.jpg",
    "img/art/2020-11-21,727,895,Aly,1,Alice Daylily,modern au,traditional,some color,bust,smiling,heart,,.jpg",
    "img/art/2020-11-21,1126,683,Aly,1,Alura Draconica,modern au,traditional,some color,bust,bonk,door frame,tall,,.jpg",
    "img/art/2020-11-21,902,1171,Aly,1,Alice Daylily,modern au,traditional,some color,torso,outfit,fit check moment,,.jpg",
    "img/art/2020-11-20,1245,1092,Aly,4,Alice Daylily,Paul Daylily,Mary Daylily,Ephius Daylily,traditional,some color,full body,the daylilies,house,rain,umbrella,family,,.jpg",
    "img/art/2020-11-18,931,1449,Aly,1,Mars,misc au,traditional,no color,full body,gun,shoot,point,hes got a gun oh no,,.jpg",
    "img/art/2020-11-17,805,1360,Aly,2,Mars,Alice Daylily,traditional,some color,full body,nightlily,height,height comparison,,.jpg",
    "img/art/2020-11-16,421,598,Aly,1,Mars,traditional,some color,torso,black hand,black,magic,melt,corrupted,,.jpg",
    "img/art/2020-11-15,1017,1324,Aly,1,Leif,traditional,some color,bust,wine,mirror,magic,ghost,,.jpg",
    "img/art/2020-11-13,1126,1348,Aly,1,Lance Amblecrown,traditional,some color,bust,redesign,,.jpg",
    "img/art/2020-11-13,971,1115,Aly,1,Lance Amblecrown,traditional,some color,full body,redesign,,.jpg",
    "img/art/2020-11-12,886,516,Aly,2,Alice Daylily,Mars,traditional,some color,bust,nightlily,shocked,blushing,,.jpg",
    "img/art/2020-11-10,889,1441,Aly,1,Paige Noname,traditional,some color,torso,redesign,smoke bombs,,.jpg",
    "img/art/2020-11-06,1019,1217,Aly,1,Keva Aibek,traditional,some color,bust,paige mom,monastery,,.jpg",
    "img/art/2020-11-06,896,1090,Aly,1,Azam Aibek,traditional,some color,bust,paige dad,monastery,,.jpg",
    "img/art/2020-11-06,1053,1686,Aly,1,Mars,traditional,some color,torso,druid,magic,,.jpg",
    "img/art/2020-11-06,1065,1353,Aly,1,Alice Daylily,traditional,some color,full body,notebook,,.jpg",
    "img/art/2020-11-05,984,1243,Aly,1,Ephius Daylily,traditional,some color,bust,eph,,.jpg",
    "img/art/2020-11-05,842,1136,Aly,1,Alice Daylily,digital,full color,bust,redesign,,.jpg",
    "img/art/2020-11-04,997,1313,Aly,1,Ponder,traditional,no color,bust,he do be ponderin i guess,,.jpg",
    "img/art/2020-10-31,1080,1346,Marlia,1,Alura Draconica,sins au,digital,full color,torso,halloween,wrath,,.jpg",
    "img/art/2020-10-31,639,810,Marlia,1,Salvier Willowmire,sins au,digital,full color,torso,halloween,gluttony,,.png",
    "img/art/2020-10-31,653,817,Marlia,1,Selthy Willowmire,sins au,digital,full color,torso,halloween,envy,,.png",
    "img/art/2020-10-27,1080,1346,Marlia,2,Selthy Willowmire,Paige Noname,ballroom au,digital,no color,torso,spinning,dancing,,.jpg",
    "img/art/2020-10-27,1080,1346,Marlia,2,Alice Daylily,Mars,ballroom au,digital,no color,torso,nightlily,dancing,,.jpg",
    "img/art/2020-10-27,1080,1346,Marlia,2,Salvier Willowmire,Alura Draconica,ballroom au,digital,no color,torso,carrying,dancing,,.jpg",
    "img/art/2020-10-24,1204,529,Aly,2,Lance Amblecrown,Mars,sins au,traditional,some color,bust,pride,sloth,comic,funny,middle finger,,.jpg",
    "img/art/2020-10-22,1000,1000,Miyuki,2,Paige Noname,Lance Amblecrown,sins au,digital,full color,bust,greed,pride,random greedy vampire,wannabe satan,,.jpg",
    "img/art/2020-10-21,1001,1726,Aly,1,Mars,sins au,traditional,some color,torso,sloth,,.jpg",
    "img/art/2020-10-21,968,1607,Aly,1,Alice Daylily,sins au,traditional,some color,full body,lust,rose,red,magic,,.jpg",
    "img/art/2020-10-21,682,1654,Aly,1,Paige Noname,sins au,traditional,some color,full body,greed,,.jpg",
    "img/art/2020-10-20,633,809,Aly,1,Alice Daylily,sins au,traditional,some color,bust,lust,,.jpg",
    "img/art/2020-10-19,1080,1074,Marlia,1,Selthy Willowmire,digital,full color,bust,icon,pfp,painting,green,,.jpg",
    "img/art/2020-10-18,829,902,Aly,1,Alura Draconica,traditional,full color,bust,cloak,,.jpg",
    "img/art/2020-10-16,1002,1717,Aly,1,Mars,traditional,full color,full body,redesign,,.jpg",
    "img/art/2020-10-15,952,1481,Aly,1,Mars,traditional,some color,full body,character design,design,design sheet,reference,,.jpg",
    "img/art/2020-10-15,1188,1377,Aly,1,Alice Daylily,traditional,some color,full body,character design,design,design sheet,reference,,.jpg",
    "img/art/2020-10-11,1080,1440,Annie,1,Mars,traditional,no color,full body,mars captured,evil squirrel,squirrel,,.jpg",
    "img/art/2020-10-05,1080,1315,Aly,1,Paul Daylily,traditional,some color,bust,talking,,.jpg",
    "img/art/2020-10-05,876,1184,Aly,1,Mary Daylily,traditional,some color,bust,side eye,,.jpg",
    "img/art/2020-10-02,1080,1920,Aly,1,Alice Daylily,digital,full color,bust,this is all a part of the plan,dragon,wallpaper,background,,.png",
    "img/art/2020-10-02,801,1076,Aly,1,Alice Daylily,traditional,some color,bust,this is all a part of the plan,dragon,sketch,,.jpg",
    "img/art/2020-10-02,1080,1288,Marlia,2,Alice Daylily,Salvier Willowmire,among us au,digital,full color,torso,imposters,innocent,sus your honor,,.jpg",
    "img/art/2020-10-02,1098,1260,Aly,1,Alice Daylily,traditional,some color,bust,side,side profile,,.jpg",
    "img/art/2020-10-01,878,1343,Aly,1,Mars,traditional,no color,bust,sketch,hes just a guy,,.jpg",
    "img/art/2020-10-01,1242,1467,Aly,1,Mars,among us au,traditional,some color,bust,annoyed,,.jpg",
    "img/art/2020-09-30,997,997,Marlia,1,Salvier Willowmire,digital,full color,bust,paiting,icon,pfp,,.jpg",
    "img/art/2020-09-30,1000,1000,Marlia,1,Paige Noname,digital,full color,bust,paiting,icon,pfp,,.jpg",
    "img/art/2020-09-30,490,549,Marlia,1,Alice Daylily,digital,full color,bust,paiting,icon,pfp,,.jpg",
    "img/art/2020-09-18,765,1040,Aly,1,Mars,traditional,no color,bust,crying,T-T,funny,,.jpg",
    "img/art/2020-09-14,1203,1365,Aly,2,Mars,Ponder,traditional,no color,bust,tea,teaching,young,young mars,studying,,.jpg",
    "img/art/2020-09-14,1242,1237,Aly,2,Alice Daylily,Mars,traditional,some color,bust,nightlily,looking,down,looking down,height,,.jpg",
    "img/art/2020-09-13,1104,1845,Aly,1,Ponder,traditional,full color,full body,druid,magic,nature,,.jpg",
    "img/art/2020-09-13,1200,1390,Aly,1,Leshie Willowmire,traditional,full color,full body,spear,,.jpg",
    "img/art/2020-09-13,1080,1318,Marlia,1,Leshie Willowmire,digital,full color,full body,original,,.png",
    "img/art/2020-09-12,1235,687,Aly,1,Sydney,traditional,full color,bust,original,gang,,.jpg",
    "img/art/2020-09-12,1242,778,Aly,1,Julius,traditional,full color,bust,original,gang,,.jpg",
    "img/art/2020-09-12,1026,1733,Aly,1,Argo,traditional,full color,bust,original,gang,,.jpg",
    "img/art/2020-09-10,636,893,Aly,1,Ephius Daylily,traditional,no color,torso,young,young ephius,leaning,sword,,.jpg",
    "img/art/2020-09-06,889,1109,Aly,1,Ephius Daylily,traditional,full color,bust,young,young ephius,smiling,,.jpg",
    "img/art/2020-09-03,881,1861,Aly,1,Alice Daylily,ballroom au,traditional,some color,torso,nightlily,omg guys she is wearin him jacket omg,,.jpg",
    "img/art/2020-09-03,1080,964,Aly,2,Alice Daylily,Mars,ballroom au,traditional,some color,torso,nightlily,heart,,.jpg",
    "img/art/2020-08-31,846,1266,Aly,2,Alice Daylily,Mars,traditional,some color,bust,hair down,casual,hug,love,heart,,.jpg",
    "img/art/2020-08-18,1242,1313,Aly,1,Paul Daylily,traditional,some color,bust,sad,crying,rain,fire,,.jpg",
    "img/art/2020-08-18,1005,950,Aly,1,Mary Daylily,traditional,some color,head,happy,heart,smiling,,.jpg",
    "img/art/2020-08-18,866,981,Aly,1,Ephius Daylily,traditional,some color,head,looking down,side,side profile,,.jpg",
    "img/art/2020-08-16,1182,500,Aly,2,Alice Daylily,Mars,traditional,some color,bust,nightlily,strawberry,question,blushing,,.jpg",
    "img/art/2020-08-08,818,818,Marlia,1,Selthy Willowmire,digital,full color,bust,painting,light,,.png",
    "img/art/2020-08-08,914,893,Aly,1,Leif,traditional,some color,bust,magic,wine,pouring,glass,bar,,.jpg",
    "img/art/2020-08-04,1242,1660,Aly,1,Leif,traditional,some color,full body,sweeping,sweeping floor,sweeping leaves,leaves,,.jpg",
    "img/art/2020-08-04,995,1159,Aly,1,Leif,traditional,no color,bust,hand,hand on hip,,.jpg",
    "img/art/2020-08-02,923,504,Aly,0,traditional,some color,,tavern,house,hallway,room,,.jpg",
    "img/art/2020-08-02,899,554,Aly,0,traditional,some color,,nightlily,house,room,tavern,,.jpg",
    "img/art/2020-08-02,1120,1186,Aly,1,Mars,traditional,some color,bust,hair down,casual,eating,drinking,steaming,tea,,.jpg",
    "img/art/2020-08-01,1242,1551,Aly,2,Alice Daylily,Mars,traditional,some color,bust,hug,sad,crying,confused,love,,.jpg",
    "img/art/2020-07-24,760,820,Aly,1,Tove,traditional,no color,bust,talking,happy,,.jpg",
    "img/art/2020-07-24,550,820,Aly,1,Tove,traditional,some color,full body,original,gremlin,,.jpg",
    "img/art/2020-07-23,1166,1299,Aly,1,Lance Amblecrown,sins au,traditional,some color,bust,pride,smoking,magic,leaning,,.jpg",
    "img/art/2020-07-13,1242,1873,Aly,1,Alice Daylily,traditional,some color,bust,sad,haircut,knife,chop,,.jpg",
    "img/art/2020-07-06,1773,1054,Aly,1,Mars,traditional,some color,bust,character,information,sheet,information sheet,description,traits,,.jpg",
    "img/art/2020-07-03,1242,1280,Aly,1,Ephius Daylily,traditional,some color,bust,can't,breathe,I can't breathe,sad,,.jpg",
    "img/art/2020-06-28,1242,1316,Aly,1,Ephius Daylily,traditional,some color,bust,sunshine,sun,happy,,.jpg",
    "img/art/2020-06-20,630,774,Marlia,1,Mars,digital,full color,bust,painting,blue,,.png",
    "img/art/2020-06-19,1242,2208,Aly,1,Paige Noname,traditional,some color,full body,redesign,tossing coin,coin,,.jpg",
    "img/art/2020-06-19,1242,1177,Aly,2,Alice Daylily,Mars,traditional,some color,bust,nightlily,sad,love,confused,cry,crying,,.jpg",
    "img/art/2020-06-19,681,808,Marlia,2,Selthy Willowmire,Saturi,digital,full color,bust,dance,formal,heart,angry,,.png",
    "img/art/2020-06-10,1163,1912,Aly,1,Alice Daylily,traditional,some color,torso,feelings are fatal,mxmtoon,sad,broken heart,hearts,,.jpg",
    "img/art/2020-06-09,1242,1339,Aly,2,Mars,Alice Daylily,traditional,some color,bust,nightlily,eyepatch,no eyepatch,,.jpg",
    "img/art/2020-06-08,1198,1255,Aly,1,Mars,traditional,some color,bust,strawberry,confused,he doesnt know what a strawberry is your honor,,.jpg",
    "img/art/2020-06-07,1100,1616,Aly,2,Alice Daylily,Mars,traditional,some color,full body,nightlily,piggyback,searching,looking,,.jpg",
    "img/art/2020-06-07,1242,1690,Aly,2,Lance Amblecrown,Kenku,traditional,some color,full body,crush,romance,love,rose,affair,,.jpg",
    "img/art/2020-06-06,1013,881,Aly,1,Mars,traditional,no color,bust,hair down,crying,sad,rain,,.jpg",
    "img/art/2020-06-05,1204,1742,Aly,1,Mary Daylily,traditional,some color,full body,balancing,plates,cups,dishes,,.jpg",
    "img/art/2020-06-05,1135,1139,Aly,1,Mars,traditional,some color,bust,annoyed,angry,flipping off,middle finger,,.jpg",
    "img/art/2020-06-02,1242,2208,Aly,2,Selthy Willowmire,Alura Draconica,traditional,no color,bust,soldiers,soldier,,.jpg",
    "img/art/2020-06-02,1242,2208,Aly,3,Mars,Alice Daylily,Salvier Willowmire,traditional,no color,bust,poets,poet,,.jpg",
    "img/art/2020-06-02,748,820,Aly,1,Nightlily kid,digital,full color,bust,child,kid,icon,,.png",
    "img/art/2020-06-01,984,1440,Aly,1,Nightlily kid,traditional,some color,torso,child,anime neck scratching,he doesnt exist anymore,,.jpg",
    "img/art/2020-05-20,4032,3024,Miyuki,3,Mars,Paige Noname,Fana Pineclaw,traditional,no color,bust,stressed and depressed,stressed,depressed,t-shirts,,.jpg",
    "img/art/2020-05-17,1040,1245,Aly,1,Salvier Willowmire,traditional,no color,torso,drinking,steaming,tea,leaning,railing,,.jpg",
    "img/art/2020-05-15,1204,1408,Aly,2,Mars,Alice Daylily,traditional,some color,full body,nightlily,carrying,cute,,.jpg",
    "img/art/2020-05-06,1242,1148,Aly,1,Mars,traditional,some color,bust,stay strong,bled,triangle,quote,,.jpg",
    "img/art/2020-05-04,1242,1360,Aly,1,Alice Daylily,traditional,some color,bust,crying,bad liar,imagine dragons,lyrics,quote,,.jpg",
    "img/art/2020-05-02,1080,1080,Marlia,1,Selthy Willowmire,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-05-02,1080,1080,Marlia,1,Salvier Willowmire,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-05-02,1080,1080,Marlia,1,Paige Noname,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-05-02,1080,1080,Marlia,1,Mars,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-05-02,1080,1080,Marlia,1,Lance Amblecrown,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-05-02,1350,1350,Marlia,1,Alura Draconica,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-05-02,1080,1080,Marlia,1,Alice Daylily,digital,full color,bust,roll20,token,,.jpeg",
    "img/art/2020-04-28,1080,1440,Marlia,1,Selthy Willowmire,traditional,no color,full body,original,,.jpg",
    "img/art/2020-04-28,1080,1440,Marlia,1,Salvier Willowmire,traditional,no color,full body,original,,.jpg",
    "img/art/2020-04-26,1072,1523,Aly,3,Alice Daylily,Ephius Daylily,Mary Daylily,traditional,no color,bust,the daylilies,family,household,,.jpg",
    "img/art/2020-04-21,1056,608,Aly,2,Alice Daylily,Mars,traditional,no color,bust,nightlily,flower,crown,flowercrown,flower crown,,.jpg",
    "img/art/2020-04-16,1242,2208,Aly,1,Alice Daylily,traditional,some color,bust,wings,halo,angel,sticky note,,.jpg",
    "img/art/2020-04-14,720,799,Aly,8,Mars,Alice,Alura,Paige,Lance,Fana,Darrak,Penelope,traditional,some color,full body,party,poster,,.jpg",
    "img/art/2020-04-14,1175,2034,Aly,1,Mars,traditional,some color,bust,sitting,crate,confused,,.jpg",
    "img/art/2020-04-14,548,770,Miyuki,1,Alice Daylily,traditional,no color,bust,notebook,heart,sad,,.png",
    "img/art/2020-04-03,3957,933,Miyuki,10,Alice,Mars,Alura,Paige,Selthy,Salvier,Lance,Darrak,Penelope,Fana,traditional,no color,head,brain,,.jpg",
    "img/art/2020-03-22,1242,1022,Aly,2,Alice Daylily,Mars,traditional,no color,full body,nightlily,chatting,heart,blushing,,.jpg",
    "img/art/2020-02-26,1140,1699,Aly,1,Alice Daylily,traditional,no color,full body,aid,the aid,dress,envelope,spy,,.jpg",
    "img/art/2020-02-15,3024,4032,Miyuki,1,Keth,traditional,no color,bust,tarot,the chariot,chariot,card,,.jpg",
    "img/art/2020-02-12,3024,4032,Miyuki,1,Alice Daylily,traditional,no color,full body,tarot,the empress,empress,card,,.jpg",
    "img/art/2020-02-03,836,947,Aly,1,Alice Daylily,traditional,some color,head,icon,token,,.jpg",
    "img/art/2020-02-03,750,845,Aly,1,Alice Daylily,digital,full color,head,icon,token,,.jpg",
    "img/art/2020-01-22,1803,1102,Aly,1,Alice Daylily,traditional,no color,full body,tree,lute,,.jpg",
    "img/art/2020-01-16,503,893,Aly,1,Alice Daylily,traditional,some color,bust,green,eyes,green eyes,,.jpg",
    "img/art/2020-01-11,1242,1525,Aly,1,Alice Daylily,traditional,no color,full body,blue,magic,swirl,,.jpg",
    "img/art/2019-12-15,492,1128,Aly,1,Alice Daylily,traditional,no color,full body,staff,lantern,mars is dead,crabrave,,.jpg",
    "img/art/2019-12-15,720,1044,Aly,1,Alice Daylily,traditional,no color,full body,staff,,.jpg",
    "img/art/2019-12-15,720,1280,Aly,1,Alice Daylily,traditional,no color,full body,ripple,staff,,.jpg",
    "img/art/2019-11-14,720,1144,Aly,1,Alice Daylily,traditional,no color,full body,winter,winter garb,garb,outfit,,.jpg",
    "img/art/2019-11-11,1200,675,Miyuki,8,Alice Daylily,Mars,Alura Draconica,Paige Noname,Lance Amblecrown,Fana Pineclaw,Darrak Karel,Penelope Namishia,digital,full color,head,cyoa,project,lineup,,.png",
    "img/art/2019-11-10,720,1153,Aly,1,Alura Draconica,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,713,973,Aly,1,Mars,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,675,1200,Aly,1,Paige Noname,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,675,1200,Aly,1,Lance Amblecrown,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,675,1200,Aly,1,Fana Pineclaw,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,675,1200,Aly,1,Darrak Karel,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,675,1200,Aly,1,Alice Daylily,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-10,674,578,Aly,1,Penelope Namishia,digital,full color,torso,game,slideshow,slides,cyoa,project,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Penelope Namishia,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Paige Noname,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Mars,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Lance Amblecrown,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Fana Pineclaw,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Darrak Karel,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Alura Draconica,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-02,768,768,Aly,1,Alice Daylily,digital,full color,head,gameshow,wimb,icon,,.png",
    "img/art/2019-11-01,2593,3457,Miyuki,1,Paige Noname,misc,random,unknown,au,traditional,no color,full body,fashion,modern,street,outfit,,.jpg",
    "img/art/2019-10-17,720,1280,Aly,1,Alice Daylily,traditional,no color,full body,generation,generation two,redesign,staff,,.jpg",
    "img/art/2019-09-06,1080,1426,Aly,1,Lance Amblecrown,traditional,no color,full body,design,final,version,final version,,.jpg",
    "img/art/2019-06-27,3024,4032,Miyuki,1,Fana Pineclaw,traditional,no color,full body,sketch,sketches,doodles,design,reference,,.jpg",
    "img/art/2019-06-20,4032,3024,Miyuki,7,Alice Daylily,Mars,Alura Draconica,Paige Noname,Lance Amblecrown,Penelope Namishia,Darrak Karel,traditional,no color,torso,who broke it,,.jpg",
    "img/art/2019-06-18,3708,1330,Miyuki,8,Alice Daylily,Mars,Alura Draconica,Paige Noname,Lance Amblecrown,Fana Pineclaw,Darrak Karel,Penelope Namishia,traditional,no color,full body,height chart,,.jpg",
    "img/art/2019-06-17,714,952,Aly,1,Mars,traditional,no color,full body,standing,staff,lantern,,.jpg",
    "img/art/2019-06-16,704,840,Miyuki,1,Fana Pineclaw,digital,full color,full body,lyric,lyrics,moth,dress,,.png",
    "img/art/2019-06-16,447,768,Miyuki,1,Alice Daylily,digital,full color,full body,lyric,lyrics,guitar,singing,music,,.png",
    "img/art/2019-06-16,330,808,Miyuki,1,Paige Noname,digital,full color,full body,lyric,lyrics,stinger,bee,arms crossed,,.png",
    "img/art/2019-06-16,304,561,Miyuki,1,Lance Amblecrown,digital,full color,full body,lyric,lyrics,bittersweet,charm,finger guns,,.jpg",
    "img/art/2019-06-16,1080,1004,Miyuki,1,Alura Draconica,digital,full color,full body,lyric,lyrics,titanium,shield,wings,,.jpg",
    "img/art/2019-01-10,497,495,Aly,1,Mars,digital,full color,bust,eyepatch,lantern,,.png",
    "img/art/2019-01-05,1536,2048,Aly,1,Penelope Namishia,traditional,no color,full body,redesign,,.jpg",
    "img/art/2019-01-05,1536,2048,Aly,1,Fana Pineclaw,traditional,no color,full body,redesign,,.jpg",
    "img/art/2019-01-05,1536,2048,Aly,1,Darrak Karel,traditional,no color,full body,redesign,,.jpg",
    "img/art/2018-11-09,2448,3264,Aly,1,Mars,traditional,no color,full body,original,,.jpg",
    "img/art/2018-10-06,1536,2048,Aly,1,Lance Amblecrown,traditional,no color,full body,original,,.jpg",
    "img/art/2018-08-20,3024,4032,Eve,1,Terry Crews,traditional,no color,full body,flower,pot,cute,,.jpg",
    "img/art/2018-08-20,3024,4024,Eve,3,Paige Noname,Alice Daylily,Keth,traditional,no color,full body,trio,,.jpg",
    "img/art/2018-08-18,564,752,Miyuki,1,Terry Crews,digital,no color,full body,goblin,,.png",
    "img/art/2018-08-18,564,752,Miyuki,1,Paige Noname,digital,no color,full body,goo,slime,ew,,.jpg",
    "img/art/2018-08-18,564,752,Miyuki,1,Paige Noname,digital,no color,full body,fire,,.png",
    "img/art/2018-08-18,564,752,Miyuki,1,Alura Draconica,digital,no color,full body,sword,stuck,floor,,.jpg",
    "img/art/2018-08-18,564,575,Miyuki,1,Alice Daylily,digital,no color,full body,hide,guard,pole,no,,.jpg",
    "img/art/2018-08-18,564,249,Miyuki,4,Alice Daylily,Alura Draconica,Paige Noname,Keth,digital,no color,full body,goblin,,.jpg",
    "img/art/2018-08-18,1350,790,Miyuki,1,Paige Noname,digital,no color,full body,rip,,.png",
    "img/art/2018-08-17,2448,3264,Aly,1,Terry Crews,traditional,no color,bust,original,old,,.jpg",
    "img/art/2018-07-26,1080,1920,Aly,4,Paige Noname,Alice Daylily,Alura Draconica,Keth,traditional,no color,full body,snapchat,umbrella,rain,,.jpg",
    "img/art/2018-07-25,2448,3264,Aly,1,Paige Noname,traditional,no color,full body,original,old,,.jpg",
    "img/art/2018-07-25,2448,3264,Aly,1,Keth,traditional,no color,full body,original,old,,.jpg",
    "img/art/2018-07-25,2448,3264,Aly,1,Keith,traditional,no color,full body,original,old,,.jpg",
    "img/art/2018-07-25,2448,3264,Aly,1,Alura Draconica,traditional,no color,full body,original,old,,.jpg",
    "img/art/2018-07-25,2448,3264,Aly,1,Alice Daylily,traditional,no color,full body,original,old,,.jpg",
];

var currentUrls = [
    ...imageUrls,
]


var imageUrlCountup= 0;
var tagArray = [];
var offset = 0; //for search logic
var added = 0; //for search logic
var curCount = 1; //how many images are currently loaded/rendered on the page

function generateImageDivs(){
    console.log('generating')
    if (currentUrls.length == 0) { //if there's no images, display box that says no results
        document.getElementById('noResults').style.display='flex';
        document.getElementById('topDisplay').style.display='none';
        document.getElementById('bottomDisplay').style.display='none';
    }
    else {
        document.getElementById('noResults').style.display='none';
        document.getElementById('topDisplay').style.display='flex';
        document.getElementById('bottomDisplay').style.display='flex';
    }
    for (let i = 0; i < 10; i++) { //loop 10 times
        document.getElementById('topDisplay').innerHTML= 'Displaying '+curCount+' of '+currentUrls.length+' images'
        document.getElementById('bottomDisplay').innerHTML= 'Displaying '+curCount+' of '+currentUrls.length+' images'
        if (imageUrlCountup >= currentUrls.length){ //stops the function if all images have been loaded
            document.getElementById('loadMoreBtn').style.display='none';
            curCount = curCount - 1;
            document.getElementById('topDisplay').innerHTML= 'Displaying '+curCount+' of '+currentUrls.length+' images'
            document.getElementById('bottomDisplay').innerHTML= 'Displaying '+curCount+' of '+currentUrls.length+' images'
            return;
        }
        else {
            document.getElementById('loadMoreBtn').style.display='flex';
        }
        var a = document.createElement("a");
        tagArray=[];
        tagArray = currentUrls[imageUrlCountup].replace('img/art/','').replace('.jpg','').replace('.png','').split(',');
        a.setAttribute('href',currentUrls[imageUrlCountup]);
        a.setAttribute('data-pswp-width',tagArray[1]);
        a.setAttribute('data-pswp-height',tagArray[2]);
        a.setAttribute('target','_blank');
        a.setAttribute('class','aImg');
        a.setAttribute('id','a'+imageUrlCountup);
        console.log(currentUrls[imageUrlCountup]);
        document.getElementById("my-gallery").appendChild(a);
        addCaption();
        addImg();
        curCount++
        if (currentUrls.length == 10){ //if there were exactly 10 images returned from search
            document.getElementById('loadMoreBtn').style.display='none';
        }
    };
    function addCaption() {
        var capt = document.createElement('span');
        figureDate();
        var tagArrayC = tagArray.slice(5).map(x => x = ' '+x);
        tagArrayC = tagArrayC.slice(0, -2);
        captionContent = 'Art by '+tagArray[3]+' on '+captDate+'.'+'<br/>'+'<br/>'+'Tags: '+tagArrayC;
        capt.innerHTML = captionContent;
        capt.setAttribute('class','pswp-caption-content');
        document.getElementById('a'+imageUrlCountup).appendChild(capt);
    }
    function addImg() {
        var img = document.createElement("img");
        img.setAttribute('class','gThumb');
        img.setAttribute('src',currentUrls[imageUrlCountup]);
        document.getElementById('a'+imageUrlCountup).appendChild(img);
        imageUrlCountup++;
    }
};


function figureDate() {
    var dateInfo = tagArray[0]
    var year = dateInfo.slice(0, 4);
    var monthNum = dateInfo.slice(5, 7);
        if (monthNum == '01') {month = 'January'}
        if (monthNum == '02') {month = 'February'}
        if (monthNum == '03') {month = 'March'}
        if (monthNum == '04') {month = 'April'}
        if (monthNum == '05') {month = 'May'}
        if (monthNum == '06') {month = 'June'}
        if (monthNum == '07') {month = 'July'}
        if (monthNum == '08') {month = 'August'}
        if (monthNum == '09') {month = 'September'}
        if (monthNum == '10') {month = 'October'}
        if (monthNum == '11') {month = 'November'}
        if (monthNum == '12') {month = 'December'}
    var day = dateInfo.slice(8, 10)
    captDate = month+' '+day+', '+year;
}

const searchInput = document.querySelector('.input')


var currentSV = ''; //current Search Value, what the user input
var SVArray = [] //search value array ^ that but an array
var searchUrlCountup = 0;
var termCountup = 0
var sTagArray = []; //search tag array, the image's tags
var filterArray = []; //list of all the terms that the user filtered out via the menu
var filterCountup = 0;


searchInput.addEventListener("change", (e) => { //listen for copy and paste
    currentSV = e.target.value
    if (currentSV && currentSV.length > 0){     //if input exists and if input is larger than 0
         currentSV = currentSV.toLowerCase().replaceAll(', ',',')
         console.log(currentSV);
    } else {
        console.log('erm what')
        return;
    };
});

searchInput.addEventListener("keydown", (e) => { //listen for typing and submitting with enter key
    currentSV = e.target.value
    if (currentSV && currentSV.length > 0){     //if input exists and if input is larger than 0
         currentSV = currentSV.toLowerCase().replaceAll(', ',',')
         console.log(currentSV);
    } else {
        console.log('erm what')
        return;
    };
    if (e.key == 'Enter') {
        handleSearchRq();
    }
})

function handleSearchRq() {
    document.getElementById('my-gallery').innerHTML = "";
    console.log('handling')
    SVArray = currentSV.split(',')
    imageUrlCountup = 0;
        //close the filter menu
        filterCont.style.display = "none"
        filterArrow.innerHTML = '∨'
    searchArraySet();
    generateImageDivs();
}

function searchArraySet(){
    currentUrls = [];
    curCount = 1;
    offset = 0;
    added = 0;
    searchUrlCountup = 0;
    filterCountup = 0
    generateFilterArray();
    for (let i = 0; i < imageUrls.length; i++) { //for however many total images there are, loop
        sTagArray=[];
        sTagArray = imageUrls[searchUrlCountup].replace('img/art/','').replace('.',',').split(',').map(v => v.toLowerCase());
        apFL(); //append first last, appends a tag that give the name in "first,last" format in addition to the initial "first last", if its any of the main seven, it adds "last" and "first last" in addition to the initial "first"
        apAU(); //append au tags, helps search bar functionality and appending them here reduces file name size
        console.log(sTagArray)

        //PUT IT IN IF IT MATCHES ANY OF THE TERMS
        for (let i = 0; i < SVArray.length; i++) { //for however many terms there are
            if (sTagArray.includes(SVArray[termCountup]) == true) { //if it contains the tag,
                console.log('yippee!')
                if (currentUrls.includes(imageUrls[searchUrlCountup]) == false) { //(and if it doesn't exist already)
                    console.log('getting you!')
                    currentUrls.push(imageUrls[searchUrlCountup]) //add it
                    added ++
                }
            }
            termCountup++
        }

    termCountup = 0;

        //CUT IT OUT IF IT DOESN'T MATCH ALL OF THE TERMS
        for (let i = 0; i < SVArray.length; i++) { //for however many terms there are
            if (sTagArray.includes(SVArray[termCountup]) == false) { //if it doesn't contain the tag
                console.log('youve been chopped')
                if (currentUrls.includes(imageUrls[searchUrlCountup]) == true) { //(and if it exists)
                    currentUrls.splice(added - 1 - offset, 1);//remove it
                    offset++
                }
            }
            termCountup++
        }

        //ALSO CUT IT IF IT'S FILTERED OUT
        for (let i = 0; i < filterArray.length; i++) { //for however many filter terms there are
            if (sTagArray.includes(filterArray[filterCountup]) == true) { //if it contains the filter term
                console.log('chopped!')
                if (currentUrls.includes(imageUrls[searchUrlCountup]) == true) { //(and if it exists)
                    currentUrls.splice(added - 1 - offset, 1);//remove it
                    offset++
                }
            }
            filterCountup++
        }
        filterCountup = 0;

    termCountup = 0;
    
    searchUrlCountup++
    }
    searchUrlCountup = 0;
    termCountup = 0;
    console.log(currentUrls)
    console.log('arraysetsearched')
}

var name1 = ''
var name2 = ''
var name3 = ''
var name4 = ''
var name5 = ''
var name6 = ''
var name7 = ''
var name8 = ''
var name9 = ''
var name10 = ''

function apFL() {
    var sCharNum = sTagArray[4];
    if (sCharNum == 0) {return}
    if (sCharNum >= 1) {
        name1 = sTagArray[5].replace(' ',',')
        sTagArray.push(name1)
    }
    if (sCharNum >= 2) {
        name2 = sTagArray[6].replace(' ',',')
        sTagArray.push(name2)
    }
    if (sCharNum >= 3) {
        name3 = sTagArray[7].replace(' ',',')
        sTagArray.push(name3)
    }
    if (sCharNum >= 4) {
        name4 = sTagArray[8].replace(' ',',')
        sTagArray.push(name4)
    }
    if (sCharNum >= 5) {
        name5 = sTagArray[9].replace(' ',',')
        sTagArray.push(name5)
    }
    if (sCharNum >= 6) {
        name6 = sTagArray[9].replace(' ',',')
        sTagArray.push(name6)
    }
    if (sCharNum >= 7) {
        name7 = sTagArray[10].replace(' ',',')
        sTagArray.push(name7)
    }
    if (sCharNum >= 8) {
        name8 = sTagArray[11].replace(' ',',')
        sTagArray.push(name8)
    }
    if (sCharNum >= 9) {
        name9 = sTagArray[12].replace(' ',',')
        sTagArray.push(name9)
    }
    if (sCharNum >= 10) {
        name10 = sTagArray[13].replace(' ',',')
        sTagArray.push(name10)
    }

    sTagArray.toString()
    var STAS = sTagArray.toString(); //String Search Tag Array
    console.log(STAS);
    sTagArray = []
    sTagArray = STAS.split(',')

    if (sTagArray.includes('Alice') == true && sTagArray.includes('Alice Daylily' == false)) {
        sTagArray.push('Alice Daylily')
        sTagArray.push('Daylily')
    }
    if (sTagArray.includes('Alura') == true && sTagArray.includes('Alura Draconica' == false)) {
        sTagArray.push('Alura Draconica')
        sTagArray.push('Draconica')
    }
    if (sTagArray.includes('Paige') == true && sTagArray.includes('Paige Noname' == false)) {
        sTagArray.push('Paige Noname')
        sTagArray.push('Noname')
    }
    if (sTagArray.includes('Selthy') == true && sTagArray.includes('Selthy Willowmire' == false)) {
        sTagArray.push('Selthy Willowmire')
        sTagArray.push('Willowmire')
    }
    if (sTagArray.includes('Salvier') == true && sTagArray.includes('Salvier Willowmire' == false)) {
        sTagArray.push('Salvier Willowmire')
        sTagArray.push('Willowmire')
    }
    if (sTagArray.includes('Lance') == true && sTagArray.includes('Lance Amblecrown' == false)) {
        sTagArray.push('Lance Amblecrown')
        sTagArray.push('Amblecrown')
    }
    if (sTagArray.includes('Fana') == true && sTagArray.includes('Fana Pineclaw' == false)) {
        sTagArray.push('Fana Pineclaw')
        sTagArray.push('Pineclaw')
    }
    if (sTagArray.includes('Darrak') == true && sTagArray.includes('Darrak Karel' == false)) {
        sTagArray.push('Darrak Karel')
        sTagArray.push('Karel')
    }
    if (sTagArray.includes('Penelope') == true && sTagArray.includes('Penelope Namishia' == false)) {
        sTagArray.push('Penelope Namishia')
        sTagArray.push('Namishia')
    }
}

function apAU() {
    var fCharNum = sTagArray[4]
    var calced = 5 + fCharNum  //this will give the array position of the au, it calculates where it should be based on the number of characters.
    // ^ if there were zero characters, the AU would be at sTagArray[5]
    if (sTagArray[calced] == 'sins au') {
        sTagArray.push('seven deadly sins au','7 deadly sins au','sins', 'seven deadly sins', '7 deadly sins')
    }
    if (sTagArray[calced] == 'modern au') {
        sTagArray.push('modern', 'hollywood', 'hollywood au', 'show', 'show au', 'tv', 'tv au', 'tv show', 'tv show au', 'film', 'film au')
    }
    if (sTagArray[calced] == 'agape au') {
        sTagArray.push('agape', 'kingdom', 'kingdom au', 'royal', 'royal au')
    }
    if (sTagArray[calced] == 'streetracer au') {
        sTagArray.push('streetracer', 'street racer', 'street racer au', 'racer', 'racer au', 'street', 'street au')
    }
    if (sTagArray[calced] == 'village au') {
        sTagArray.push('village', 'town', 'town au')
    }
    if (sTagArray[calced] == 'band au') {
        sTagArray.push('band', 'concert', 'concert au')
    }
    if (sTagArray[calced] == 'ballroom au') {
        sTagArray.push('ballroom', 'formal wear', 'formal au', 'formal', 'fancy')
    }
    if (sTagArray[calced] == 'among us au') {
        sTagArray.push('among us', 'amogus', 'amogus au', 'amongus', 'amongus au', 'sus')
    }
    if (sTagArray[calced] == 'cyberpunk au') {
        sTagArray.push('cyberpunk', 'cyber punk', 'cyber punk au', 'tech', 'tech au')
    }
    if (sTagArray[calced] == 'misc au') {
        sTagArray.push('misc', 'random', 'random au', 'unknown', 'unknown au')
    }
}

function generateFilterArray() {
    filterArray = []
    //will grab all the states of the checkboxes and populate filterArray with the tags to be filtered out
    if (document.getElementById('alice').checked == true) {filterArray.push('alice')}
    if (document.getElementById('mars').checked == true) {filterArray.push('mars')}
    if (document.getElementById('alura').checked == true) {filterArray.push('alura')}
    if (document.getElementById('paige').checked == true) {filterArray.push('paige')}
    if (document.getElementById('lance').checked == true) {filterArray.push('lance')}
    if (document.getElementById('sel').checked == true) {filterArray.push('selthy')}
    if (document.getElementById('sal').checked == true) {filterArray.push('salvier')}
    if (document.getElementById('fana').checked == true) {filterArray.push('fana')}
    if (document.getElementById('penelope').checked == true) {filterArray.push('penelope')}
    if (document.getElementById('darrak').checked == true) {filterArray.push('darrak')}
    if (document.getElementById('keth').checked == true) {filterArray.push('keth')}
    if (document.getElementById('keith').checked == true) {filterArray.push('keith')}
    if (document.getElementById('terry').checked == true) {filterArray.push('terry')}
    if (document.getElementById('leif').checked == true) {filterArray.push('leif')}
    if (document.getElementById('saturi').checked == true) {filterArray.push('saturi')}
    if (document.getElementById('ponder').checked == true) {filterArray.push('ponder')}
    if (document.getElementById('osyris').checked == true) {filterArray.push('osyris')}
    if (document.getElementById('leo').checked == true) {filterArray.push('leo')}
    if (document.getElementById('antagonist').checked == true) {filterArray.push('antagonist')}
    if (document.getElementById('mary').checked == true) {filterArray.push('mary')}
    if (document.getElementById('paul').checked == true) {filterArray.push('paul')}
    if (document.getElementById('ephius').checked == true) {filterArray.push('ephius')}
    if (document.getElementById('tove').checked == true) {filterArray.push('tove')}
    if (document.getElementById('julius').checked == true) {filterArray.push('julius')}
    if (document.getElementById('sydney').checked == true) {filterArray.push('sydney')}
    if (document.getElementById('argo').checked == true) {filterArray.push('argo')}
    if (document.getElementById('nk').checked == true) {filterArray.push('nightlily kid')}
    if (document.getElementById('keva').checked == true) {filterArray.push('keva')}
    if (document.getElementById('azam').checked == true) {filterArray.push('azam')}
    if (document.getElementById('hadiyah').checked == true) {filterArray.push('hadiyah')}
    if (document.getElementById('kenku').checked == true) {filterArray.push('kenku')}
    if (document.getElementById('leshie').checked == true) {filterArray.push('leshie')}
    if (document.getElementById('aly').checked == true) {filterArray.push('aly')}
    if (document.getElementById('marlia').checked == true) {filterArray.push('marlia')}
    if (document.getElementById('miyuki').checked == true) {filterArray.push('miyuki')}
    if (document.getElementById('annie').checked == true) {filterArray.push('annie')}
    if (document.getElementById('chris').checked == true) {filterArray.push('chris')}
    if (document.getElementById('eve').checked == true) {filterArray.push('eve')}
    if (document.getElementById('ai').checked == true) {filterArray.push('ai')}
    if (document.getElementById('sins').checked == true) {filterArray.push('sins au')}
    if (document.getElementById('modern').checked == true) {filterArray.push('modern au')}
    if (document.getElementById('agape').checked == true) {filterArray.push('agape au')}
    if (document.getElementById('streetracer').checked == true) {filterArray.push('streetracer au')}
    if (document.getElementById('village').checked == true) {filterArray.push('village au')}
    if (document.getElementById('band').checked == true) {filterArray.push('band au')}
    if (document.getElementById('ballroom').checked == true) {filterArray.push('ballroom au')}
    if (document.getElementById('amongus').checked == true) {filterArray.push('among us au')}
    if (document.getElementById('cyberpunk').checked == true) {filterArray.push('cyberpunk au')}
    if (document.getElementById('misc').checked == true) {filterArray.push('misc au')}
    if (document.getElementById('traditional').checked == true) {filterArray.push('traditional')}
    if (document.getElementById('digital').checked == true) {filterArray.push('digital')}
    if (document.getElementById('ncolor').checked == true) {filterArray.push('no color')}
    if (document.getElementById('scolor').checked == true) {filterArray.push('some color')}
    if (document.getElementById('fcolor').checked == true) {filterArray.push('full color')}
    if (document.getElementById('head').checked == true) {filterArray.push('head')}
    if (document.getElementById('bust').checked == true) {filterArray.push('bust')}
    if (document.getElementById('torso').checked == true) {filterArray.push('torso')}
    if (document.getElementById('fbody').checked == true) {filterArray.push('full body')}
    if (document.getElementById('png').checked == true) {filterArray.push('png')}
    if (document.getElementById('jpg').checked == true) {filterArray.push('jpg')}
    if (document.getElementById('jpeg').checked == true) {filterArray.push('jpeg')}
    //make the texts that tell you how many filters are 
    var filterNum = filterArray.length;
    document.getElementById('filtersDisplay').innerHTML = filterNum+" filters currently applied."
    if (filterNum == 1) {
        document.getElementById('filtersDisplay').innerHTML = filterNum+" filter currently applied."
    }
}

{ //these are the listeners for the select all feature in the filter menu. just in braces so i can collapse it
    document.querySelector('#charSelectAll').addEventListener("change", () => { //change is for radio buttons
        var inputs = document.querySelectorAll('.char');
        var selectAll = document.getElementById('charSelectAll')
        console.log('woowee i look just like buddy hollyyy')
        if (selectAll.checked == true) {  //if select all is checked 
            for (var i = 0; i < inputs.length; i++) { //loop through and check all the boxes there
                inputs[i].checked = true;
            }
        }
        else { //if select all is unchecked
            for (var i = 0; i < inputs.length; i++) { //loop through and uncheck all the boxes there
                inputs[i].checked = false;
            }
        }
    });
    document.querySelector('#bcharSelectAll').addEventListener("change", () => {
        var inputs = document.querySelectorAll('.bchar');
        var selectAll = document.getElementById('bcharSelectAll')
        if (selectAll.checked == true) {
            for (var i = 0; i < inputs.length; i++) {
                inputs[i].checked = true;
            }
        }
        else {
            for (var i = 0; i < inputs.length; i++) {
                inputs[i].checked = false;
            }
        }
    });
    document.querySelector('#artistSelectAll').addEventListener("change", () => {
        var inputs = document.querySelectorAll('.artist');
        var selectAll = document.getElementById('artistSelectAll')
        if (selectAll.checked == true) {
            for (var i = 0; i < inputs.length; i++) {
                inputs[i].checked = true;
            }
        }
        else {
            for (var i = 0; i < inputs.length; i++) {
                inputs[i].checked = false;
            }
        }
    });
    document.querySelector('#auSelectAll').addEventListener("change", () => {
        var inputs = document.querySelectorAll('.au');
        var selectAll = document.getElementById('auSelectAll')
        if (selectAll.checked == true) {
            for (var i = 0; i < inputs.length; i++) {
                inputs[i].checked = true;
            }
        }
        else {
            for (var i = 0; i < inputs.length; i++) {
                inputs[i].checked = false;
            }
        }
    });
}

function resetAll(){
    imageUrlCountup = 0;
    curCount = 1;
    currentUrls = []
    currentUrls = [
        ...imageUrls,
    ]
    currentSV = '';
    filterArray = [];
    generateImageDivs();
}

var filterCont = document.getElementById('filterCont')
var filterArrow = document.getElementById('filterArrow')

function toggleFilterMenu() {
    if (filterCont.style.display == "flex") { //if filter content is visible 
        filterCont.style.display = "none" //close it
        console.log('closing')
        filterArrow.innerHTML = '∨'
    }
    else { //if it's not visible
        filterCont.style.display = "flex" //open it
        console.log('opening')
        filterArrow.innerHTML = '∧'
    }
};

var sortCont = document.getElementById('sortCont')
var sortArrow = document.getElementById('sortArrow')

function toggleSortMenu() {
    if (sortCont.style.display == "flex") { //if exclude is visible
        sortCont.style.display = "none" //close it
        sortArrow.innerHTML = '∨'
    }
    else { //if its not visible
        sortCont.style.display = "flex" //open it
        sortArrow.innerHTML = '∧'
    }
}

    